version: '3.8'
services:
  kibana:
    image: 'kibana:7.8.1'
    container_name: 'kibana'
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    # volumes:
    #   - type: bind
    #     source: ./kibana-volume
    #     target: /usr/share/kibana/config/
    ports:
      - 5601:5601
    networks: 
      - default
networks:
  default:
    external: 
      name: elk
  
  
